apiVersion: v1
kind: Pod
metadata:
  name: node-mon
spec:
  containers:
  - name: node-mon
    image: coolage/node-mon:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
    - name: ca-pemstore
      mountPath: /etc/ssl/certs/my.pem
      subPath: my.pem
      readOnly: false
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: config-file-aws-secret
            key: awsAccessKeyId
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: config-file-aws-secret
            key: awsSecretAccessKey
    ports:
    - containerPort: 8880
  volumes:
  - name: config
    configMap:
      name: config-file-cm
  - name: aws
    configMap:
      name: config-file-aws
  - name: ca-pemstore
    configMap:
      name: ca-pemstore
  serviceAccount: node-mon
